version: "3"

services:
  # main_api:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   ports: [1000:1000]
  #   environment: [PORT=1000]
  #   restart: unless-stopped

  elastic:
    image: 'bitnami/elasticsearch:latest'
    ports: [9200:9200]
    volumes: [elastic_data:/bitnami/elasticsearch/data]
    restart: unless-stopped
    

  kibana:
    image: 'bitnami/kibana:latest'
    ports: [5601:5601]
    environment:
      KIBANA_ELASTICSEARCH_URL : elastic
    depends_on:
      - elastic
    restart: unless-stopped


volumes:
  elastic_data:
